# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/HapusEvent.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 354)
        Dialog.setStyleSheet("background-color: rgb(81, 81, 81);")
        self.lblTitleDelete = QtWidgets.QLabel(Dialog)
        self.lblTitleDelete.setGeometry(QtCore.QRect(10, 110, 428, 74))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitleDelete.setFont(font)
        self.lblTitleDelete.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblTitleDelete.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitleDelete.setWordWrap(True)
        self.lblTitleDelete.setObjectName("lblTitleDelete")
        self.frameInfoProduk = QtWidgets.QFrame(Dialog)
        self.frameInfoProduk.setGeometry(QtCore.QRect(10, 191, 428, 74))
        self.frameInfoProduk.setMinimumSize(QtCore.QSize(0, 60))
        self.frameInfoProduk.setStyleSheet("background-color: rgb(221, 116, 113);\n"
"background-color: rgb(255, 214, 193);")
        self.frameInfoProduk.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameInfoProduk.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameInfoProduk.setObjectName("frameInfoProduk")
        self.lblNamaEvent = QtWidgets.QLabel(self.frameInfoProduk)
        self.lblNamaEvent.setGeometry(QtCore.QRect(80, 30, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblNamaEvent.setFont(font)
        self.lblNamaEvent.setStyleSheet("color: rgb(255, 29, 32);")
        self.lblNamaEvent.setObjectName("lblNamaEvent")
        self.lblLogo = QtWidgets.QLabel(Dialog)
        self.lblLogo.setGeometry(QtCore.QRect(10, 14, 428, 89))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.lblLogo.setFont(font)
        self.lblLogo.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLogo.setObjectName("lblLogo")
        self.buttonArea = QtWidgets.QWidget(Dialog)
        self.buttonArea.setGeometry(QtCore.QRect(10, 272, 428, 74))
        self.buttonArea.setObjectName("buttonArea")
        self.btnBatal = QtWidgets.QPushButton(self.buttonArea)
        self.btnBatal.setGeometry(QtCore.QRect(80, 20, 121, 45))
        self.btnBatal.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnBatal.setFont(font)
        self.btnBatal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnBatal.setStyleSheet("color: rgb(255, 255, 255);")
        self.btnBatal.setObjectName("btnBatal")
        self.btnHapus = QtWidgets.QPushButton(self.buttonArea)
        self.btnHapus.setGeometry(QtCore.QRect(220, 20, 141, 45))
        self.btnHapus.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnHapus.setFont(font)
        self.btnHapus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnHapus.setStyleSheet("background-color: rgb(255, 46, 74);\n"
"color: rgb(255, 255, 255);")
        self.btnHapus.setObjectName("btnHapus")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblTitleDelete.setText(_translate("Dialog", "Hapus Event?"))
        self.lblNamaEvent.setText(_translate("Dialog", "ID: 001 - 11:11 Super Sale (ML)"))
        self.lblLogo.setText(_translate("Dialog", "⚠️"))
        self.btnBatal.setText(_translate("Dialog", "Batal"))
        self.btnHapus.setText(_translate("Dialog", "Ya, Hapus"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
