# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/HapusProduk.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialogDelete(object):
    def setupUi(self, dialogDelete):
        dialogDelete.setObjectName("dialogDelete")
        dialogDelete.resize(450, 354)
        dialogDelete.setStyleSheet("background-color: rgb(81, 81, 81);")
        self.verticalLayout = QtWidgets.QVBoxLayout(dialogDelete)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblLogo = QtWidgets.QLabel(dialogDelete)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.lblLogo.setFont(font)
        self.lblLogo.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLogo.setObjectName("lblLogo")
        self.verticalLayout.addWidget(self.lblLogo)
        self.lblTitleDelete = QtWidgets.QLabel(dialogDelete)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitleDelete.setFont(font)
        self.lblTitleDelete.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblTitleDelete.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitleDelete.setWordWrap(True)
        self.lblTitleDelete.setObjectName("lblTitleDelete")
        self.verticalLayout.addWidget(self.lblTitleDelete)
        self.frameInfoProduk = QtWidgets.QFrame(dialogDelete)
        self.frameInfoProduk.setMinimumSize(QtCore.QSize(0, 60))
        self.frameInfoProduk.setStyleSheet("background-color: rgb(221, 116, 113);\n"
"background-color: rgb(255, 214, 193);")
        self.frameInfoProduk.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameInfoProduk.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameInfoProduk.setObjectName("frameInfoProduk")
        self.lblInfoProduk = QtWidgets.QLabel(self.frameInfoProduk)
        self.lblInfoProduk.setGeometry(QtCore.QRect(40, 30, 361, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblInfoProduk.setFont(font)
        self.lblInfoProduk.setStyleSheet("color: rgb(255, 29, 32);")
        self.lblInfoProduk.setObjectName("lblInfoProduk")
        self.verticalLayout.addWidget(self.frameInfoProduk)
        self.buttonArea = QtWidgets.QWidget(dialogDelete)
        self.buttonArea.setObjectName("buttonArea")
        self.btnBatal = QtWidgets.QPushButton(self.buttonArea)
        self.btnBatal.setGeometry(QtCore.QRect(80, 20, 121, 45))
        self.btnBatal.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnBatal.setFont(font)
        self.btnBatal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnBatal.setStyleSheet("color: rgb(255, 255, 255);")
        self.btnBatal.setObjectName("btnBatal")
        self.btnHapus = QtWidgets.QPushButton(self.buttonArea)
        self.btnHapus.setGeometry(QtCore.QRect(220, 20, 141, 45))
        self.btnHapus.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnHapus.setFont(font)
        self.btnHapus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnHapus.setStyleSheet("background-color: rgb(255, 46, 74);\n"
"color: rgb(255, 255, 255);")
        self.btnHapus.setObjectName("btnHapus")
        self.verticalLayout.addWidget(self.buttonArea)

        self.retranslateUi(dialogDelete)
        QtCore.QMetaObject.connectSlotsByName(dialogDelete)

    def retranslateUi(self, dialogDelete):
        _translate = QtCore.QCoreApplication.translate
        dialogDelete.setWindowTitle(_translate("dialogDelete", "Konfirmasi Hapus"))
        self.lblLogo.setText(_translate("dialogDelete", "⚠️"))
        self.lblTitleDelete.setText(_translate("dialogDelete", "Hapus Produk?"))
        self.lblInfoProduk.setText(_translate("dialogDelete", "ID: 001 - Mobile Legends Diamond (100)"))
        self.btnBatal.setText(_translate("dialogDelete", "Batal"))
        self.btnHapus.setText(_translate("dialogDelete", "Ya, Hapus"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialogDelete = QtWidgets.QDialog()
    ui = Ui_dialogDelete()
    ui.setupUi(dialogDelete)
    dialogDelete.show()
    sys.exit(app.exec_())
